version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped 